Fix import in i18n macro module
This change fixes the test suite, which is currently failing with
```
Traceback (most recent call last):
  File "/Users/nicksay/dev/spitfire/spitfire/compiler/analyzer_test.py", line 557, in test_allow_raw_macro_no_error
    semantic_analyzer.get_ast()
  File "spitfire/test_util.py", line 119, in __call__
    result = self._func(*args, **kwargs)
  File "spitfire/compiler/analyzer.py", line 87, in get_ast
    ast_node_list = self.build_ast(self.parse_root)
  File "spitfire/compiler/analyzer.py", line 99, in build_ast
    ast_node_list = method(node)
  File "spitfire/compiler/analyzer.py", line 155, in analyzeTemplateNode
    built_nodes = self.build_ast(pn)
  File "spitfire/compiler/analyzer.py", line 99, in build_ast
    ast_node_list = method(node)
  File "spitfire/compiler/analyzer.py", line 402, in analyzeDefNode
    function.extend(self.build_ast(pn))
  File "spitfire/compiler/analyzer.py", line 99, in build_ast
    ast_node_list = method(node)
  File "spitfire/compiler/analyzer.py", line 467, in analyzeMacroNode
    return self.handleMacro(pnode, macro_function, macro_parse_rule)
  File "spitfire/compiler/analyzer.py", line 430, in handleMacro
    macro_output = macro_function(pnode, kargs_map, self.compiler)
  File "spitfire/compiler/macros/i18n.py", line 56, in macro_i18n
    macro_content_ast = spitfire.compiler.util.parse(macro_node.value,
NameError: global name 'spitfire' is not defined
```

Closes #26