Fix codegen for EchoNode to ensure it is marked as using buffer write.
This change fixes the test suite, which is currently failing with
```
Traceback (most recent call last):
  File "scripts/crunner.py", line 142, in process_file
    current_output = template.main().encode('utf8')
NameError: global name '_buffer_write' is not defined
```

Progress on #26